# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-05 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
        ("dashboard", "0003_auto_20190305_0916"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="student",
            field=models.ManyToManyField(to="account.Student"),
        )
    ]
