# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-05 10:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("dashboard", "0005_auto_20190305_0959")]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="subscription_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lessons",
                to="dashboard.Subscription",
            ),
        )
    ]
