# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-05 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("dashboard", "0006_auto_20190305_1049")]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="student",
            field=models.ManyToManyField(related_name="students", to="account.Student"),
        )
    ]
