# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-05 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190305_1049'),
        ('dashboard', '0007_auto_20190305_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='student',
        ),
        migrations.AddField(
            model_name='lesson',
            name='student_id',
            field=models.ManyToManyField(to='account.Student'),
        ),
    ]
