# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-07 19:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20190307_0859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'lesson_id'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'subscription_id'},
        ),
    ]
