# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-14 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_auto_20190314_1000"),
        ("dashboard", "0013_auto_20190314_1000"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="account",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to="account.Account",
            ),
            preserve_default=False,
        )
    ]
