# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-28 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190228_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='insert_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
