# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-14 10:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("account", "0002_auto_20190305_1049")]

    operations = [
        migrations.AlterModelOptions(
            name="account", options={"verbose_name": "Account"}
        ),
        migrations.AlterModelOptions(
            name="student", options={"verbose_name": "Student"}
        ),
    ]
