# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-14 10:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("account", "0003_auto_20190314_1000")]

    operations = [
        migrations.RenameField(
            model_name="student", old_name="account_id", new_name="account"
        ),
        migrations.AlterUniqueTogether(
            name="student",
            unique_together=set([("account", "first_name", "last_name")]),
        ),
    ]
