# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-01 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20190301_1014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'account'},
        ),
        migrations.AlterField(
            model_name='student',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='account.Account'),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=set([('name', 'password')]),
        ),
    ]
